function write_spice_file(d, c)

f_name = 'matlab.sp';

f = fopen(f_name, 'w');
fprintf(f, '* Autogenerated spice file from design_project.m\n');
fprintf(f, '\n');
fprintf(f, '* ee114 device models\n');
fprintf(f, '.include /usr/class/ee214/hspice/ee214_hspice.sp\n');

fprintf(f, '\n');
fprintf(f, 'r1  n_vdd n_x   %0.1f\n', d.r_1);
fprintf(f, 'r2  n_vdd n_w   %0.1f\n', d.r_2);
fprintf(f, 'rf  n_ox  n_i   %0.1f\n', d.r_f);

fprintf(f, '\n');
fprintf(f, 'cl        n_o   0   %0.1ff\n', c.c_l*1e15);
fprintf(f, 'cd        n_i   0   %0.1ff\n', c.c_d*1e15);
fprintf(f, 'c_magic_0 n_z   0   1.0\n');
fprintf(f, 'cf        n_ox  n_i %0.1ff\n', d.c_f*1e15);

fprintf(f, '\n');
fprintf(f, 'm1    n_x   n_g   n_i   0     nmos214       w=%0.1fu l=%0.2fu\n', d.m1.w, d.m1.l);
fprintf(f, 'm2    n_y   n_x   n_z   0     nmos214       w=%0.1fu l=%0.2fu\n', d.m2.w, d.m2.l);
fprintf(f, 'm3    n_w   n_c   n_y   0     nmos214       w=%0.1fu l=%0.2fu\n', d.m3.w, d.m3.l);
fprintf(f, 'm4    n_vdd n_w   n_o   0     nmos214       w=%0.1fu l=%0.2fu\n', d.m4.w, d.m4.l);

fprintf(f, '\n');
fprintf(f, 'mb1   n_i   n_b   0     0     nmos214       w=%0.1fu l=%0.2fu\n', d.mb1.w, d.mb1.l);
fprintf(f, 'mb2   n_z   n_b   0     0     nmos214       w=%0.1fu l=%0.2fu\n', d.mb2.w, d.mb2.l);
fprintf(f, 'mb3   n_o   n_b   0     0     nmos214       w=%0.1fu l=%0.2fu\n', d.mb3.w, d.mb3.l);

fprintf(f, '\n');
fprintf(f, 'vdd   n_vdd   0     %0.1f\n', c.vdd);
fprintf(f, 'vg    n_g     0     %0.3f\n', d.v_g);
fprintf(f, 'vc    n_c     0     %0.3f\n', d.v_c);
fprintf(f, 'vb    n_b     0     %0.3f\n', d.v_b);
fprintf(f, 'vx    n_o     n_ox  0\n');

fprintf(f, 'is    n_i     0   DC=0  AC=1\n');

fprintf(f, '.op\n');
fprintf(f, '.ac dec 1000 1e6 1000e9\n');
fprintf(f, '.lstb mode=single vsource=vx\n');
fprintf(f, '.probe ac lstb(db) lstb(p)\n');
fprintf(f, '.pz v(n_o) is\n');
fprintf(f, '.noise v(n_o) is\n');
fprintf(f, '.option post brief accurate\n');
fprintf(f, '.end\n');

end
